[tool.pyright]
venvPath = "."
venv = "venv"
pythonVersion = "3.11"
pythonPlatform = "Windows"
executionEnvironments = [
    { root = "backend", pythonVersion = "3.11", pythonPlatform = "Windows", extraPaths = ["backend"] }
]
include = ["backend"]
exclude = ["**/node_modules", "**/__pycache__", "venv"]
typeCheckingMode = "basic"
reportMissingImports = false
reportMissingTypeStubs = false

[tool.pylint]
init-hook = "import sys; sys.path.insert(0, 'backend')"

